import type { PipelineParams } from './index'

export type FilterPreset = 'conservative' | 'balanced' | 'permissive' | 'logAll'

export const FILTER_PRESETS: Record<FilterPreset, PipelineParams> = {
  conservative: {
    minDetectorConfidence: 0.55,
    minOcrConfidence: 0.70,
    minCharConfidence: 0.45,
    minBboxAreaPx: 1200,
    minPlateLen: 5,
    maxPlateLen: 10,
    stabilizerWindowMs: 2500,
    consensusK: 3,
    consensusN: 5,
    fuzzyDistance: 1,
    stationarySpeedThresholdKph: 5,
    bboxDriftMaxStationaryPx: 40,
    motionWindowMs: 3000,
    timeWindowMs: 60_000,
    geoRadiusM: 50,
    retriggerWindowMs: 300_000,
    retriggerRadiusM: 500,
    speedAwareRadius: true,
  },
  balanced: {
    minDetectorConfidence: 0.45,
    minOcrConfidence: 0.55,
    minCharConfidence: 0.35,
    minBboxAreaPx: 800,
    minPlateLen: 4,
    maxPlateLen: 10,
    stabilizerWindowMs: 2000,
    consensusK: 2,
    consensusN: 4,
    fuzzyDistance: 1,
    stationarySpeedThresholdKph: 5,
    bboxDriftMaxStationaryPx: 60,
    motionWindowMs: 3000,
    timeWindowMs: 60_000,
    geoRadiusM: 50,
    retriggerWindowMs: 300_000,
    retriggerRadiusM: 500,
    speedAwareRadius: true,
  },
  permissive: {
    minDetectorConfidence: 0.30,
    minOcrConfidence: 0.40,
    minCharConfidence: 0.20,
    minBboxAreaPx: 400,
    minPlateLen: 3,
    maxPlateLen: 12,
    stabilizerWindowMs: 1500,
    consensusK: 1,
    consensusN: 3,
    fuzzyDistance: 1,
    stationarySpeedThresholdKph: 3,
    bboxDriftMaxStationaryPx: 120,
    motionWindowMs: 3000,
    timeWindowMs: 60_000,
    geoRadiusM: 50,
    retriggerWindowMs: 120_000,
    retriggerRadiusM: 250,
    speedAwareRadius: true,
  },
  logAll: {
    minDetectorConfidence: 0,
    minOcrConfidence: 0,
    minCharConfidence: 0,
    minBboxAreaPx: 0,
    minPlateLen: 0,
    maxPlateLen: 999,
    stabilizerWindowMs: 1,
    consensusK: 1,
    consensusN: 1,
    fuzzyDistance: 0,
    stationarySpeedThresholdKph: 0,
    bboxDriftMaxStationaryPx: 1e9,
    motionWindowMs: 1,
    timeWindowMs: 0,
    geoRadiusM: 0,
    retriggerWindowMs: 0,
    retriggerRadiusM: 0,
    speedAwareRadius: false,
  },
}

export const DEFAULT_PRESET: FilterPreset = 'balanced'
